#Server
server:
  port: 8070
#Management
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#Spring
spring:
  application:
    name: order-history-service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: order_history
#Axon
axon:
  serializer:
    general: jackson
